server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderDb?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  application:
    name: ORDER-SERVICE

  cloud:
    stream:
      function:
        definition: orderSupplier
      bindings: # here "out" represent publisher to the topic
        orderSupplier-out-0: # here 0 is any number. we can specify any number of topics here as like this
          destination: order-event  # This is the topic name we are going to publish